export {default as Home} from './Home/Home'
export {default as Login} from './Login/Login'
export {default as Register} from './Register/Register'
export {default as Catalogo} from './Catalogo/Catalogo'
export {default as Detalle} from './DetalleProducto/DetalleProducto'
export {default as Comparacion} from './Comparacion/Comparacion'
export {default as Carrito} from './Carrito/Carrito'
export {default as Envio} from './Envio/Envio'